### ISSUE TITLE
Computer does not power off after upgrade from Kernel 5.15.0-117 to 6.8.039

### ISSUE THREAD

**Issue by GPard1009** [linuxmint/mintupgrade#105]
Hi,
I am running on Mint 21.3 Kernel: Linux 5.15.0-117-generic I have upgraded to Kernel 6.8.039. The result was that the computer did not power off after shutting down Mint. I can reproduce it.

Chassis: desktop
Operating System: Linux Mint 21.3                 
Architecture: x86-64
Hardware Vendor: GEEKOM
Hardware Model: IT12

acpi -a returns Adapter 0: off-line
acpi -b returns nothing

And I also have problems with the upgrade to Mint 22. See -> https://github.com/linuxmint/mintupgrade/issues/104

cheers
G.Pard

**Comment by clefebvre** [comment]
This is upstream from us and not related to the upgrade itself.
