### ISSUE TITLE
The terminal process did not close automatically, is this okay?

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mintupgrade#11]
Hi
I tried it.
It has a good impression.
I put a command in the terminal and started
At completion, the terminal process did not close automatically, is this okay?
![スクリーンショット 2022-04-19 08-10-59](https://user-images.githubusercontent.com/78515193/163909041-5121c905-3b6f-4ae8-90de-affee586d8e7.png)

**Comment by clefebvre** [comment]
Yes, that's perfectly OK. At that stage you can reboot the computer and you're done.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupgrade/commit/10576d9fab844cf96c99775ee5e34b79119a9f53
