### ISSUE TITLE
Improvement - Add a progress bar (and maybe a preview of command lines)

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/mintupgrade#12]
Hey :cat: 

**First of all, thanks a lot for this tool!**
Even, it's still a beta, it just works fine according to my tests on VM.

However, it could great to have a progress bar for the final version because without the terminal we are not sure that the tool is not stuck during the upgrade. Also, maybe it could be great to have a preview of command lines (like during daily updates) for curious people and also to help in case of issues.

**Comment by clefebvre** [comment]
I'm sorry, unfortunately we're limited by what we can do with APT libs (python-apt, aptdaemon). Even apt-get sometimes doesn't give us the output we need (return codes on update errors for instance). For this reason we decided to rely on the terminal for troubleshooting and we sometimes do things twice to detect errors (for instance apt-get update is done with apt-get for you to see the output in the terminal in case of errors, but also via python-apt for us to detect errors reliably).

We can't show progress bars. We could break steps into smaller steps in some cases, but the ones which take time are already only doing one thing.
