### ISSUE TITLE
Upgrade Tool shows that it is for LinuxMint 21 

### ISSUE THREAD

**Issue by JiangXL** [linuxmint/mintupgrade#13]
After `apt install mintupgrade` and `apt install mintupgrade`, upgrade tools recognizes LMDE as Linux Mint 21. 
![image](https://user-images.githubusercontent.com/5670700/164892957-19f0fa93-f656-40f0-b573-ca0091f5cd0e.png)

It is weird. What is wrong?

**Comment by clefebvre** [comment]
Is debian-system-adjustments installed?

**Comment by JiangXL** [comment]
Thanks! 
After installation of debian-system-adjustments, I can upgrade LMDE5 normally.
