### ISSUE TITLE
`Additional Repositories` link updates

### ISSUE THREAD

**Issue by ovari** [linuxmint/mintupgrade#17]
How will the Linux Mint upgrade handle `Additional Repositories`?

![image](https://user-images.githubusercontent.com/17465872/166137702-159cba41-3cf1-44a7-b5ce-a161fb2927db.png)

[Jami](https://jami.net/download-jami-linux/) for:
* LMDE 4 link is https://dl.jami.net/ring-manual/debian_10/jami-all_amd64.deb
* LMDE 5 link is https://dl.jami.net/ring-manual/debian_11/jami-all_amd64.deb

For:
* Linux Mint 20 https://dl.jami.net/ring-manual/ubuntu_20.04/jami-all_amd64.deb
* Linux Mint 21 https://dl.jami.net/ring-manual/ubuntu_22.04/jami-all_amd64.deb

Thank you

**Comment by candrapersada** [comment]
[WineHQ](https://wiki.winehq.org) for:
* LMDE 4 https://dl.winehq.org/wine-builds/debian/dists/buster/winehq-buster.sources
* LMDE 5 https://dl.winehq.org/wine-builds/debian/dists/bullseye/winehq-bullseye.sources

For:
* Linux Mint 20 https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources
* Linux Mint 21 https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources

**Comment by clefebvre** [comment]
It will check the codename for the repository. So for instance, it will accept to keep the repository if it sees it supports jammy.
