### ISSUE TITLE
automatically install and remove mintupgrade

### ISSUE THREAD

**Issue by candrapersada** [linuxmint/mintupgrade#19]
will there be a feature in the future to automatically install and remove `mintupgrade` without using `apt install mintupgrade` and `apt remove mintupgrade`?

**Comment by OdinVex** [comment]
I think it might be better to integrate this tool into [`Mint Update / Update Manager`](https://github.com/linuxmint/mintupdate).

**Comment by Jeremy7701** [comment]
Since mintupgrade is so small, so long as you run the latest version at the appropriate time, there is no harm in leaving it on your system.

**Comment by OdinVex** [comment]
> Since mintupgrade is so small, so long as you run the latest version at the appropriate time, there is no harm in leaving it on your system.

Quite true, though I'd still like to eventually see the functionality put all into one location, [`Mint Update / Update Manager`](https://github.com/linuxmint/mintupdate). I think it'd be more manageable after integrated. Then again, I like singular update managers. \*shrug\*

**Comment by clefebvre** [comment]
There could be but for now we also like to time this with announcements and accompany people as they upgrade with a comment section and all.
