### ISSUE TITLE
Concerns

### ISSUE THREAD

**Issue by eband** [linuxmint/mintupgrade#2]
Is mintupgrade2 **mandatory** for a successful upgrade, or can I use command line as well?

**Comment by Jeremy7701** [comment]
I tried the incomplete `mintupgrade2` (in a VM) and it has a long way to go before it can be used for a LMDE4 upgrade.
**Assuming I ran it correctly**, too many faults at this stage of development to be worth reporting.

I too would prefer one of those simple CLI upgrades, such as was provided from LMDE3 -> LMDE4.

**Comment by eband** [comment]
Hear! Hear!

**Comment by clefebvre** [comment]
> Is mintupgrade2 **mandatory** for a successful upgrade, or can I use command line as well?

Well, it's the recommended tool for the upgrade, but no, you can upgrade manually your own way if you know what you are doing.
