### ISSUE TITLE
Rollback changes made to apt sources list

### ISSUE THREAD

**Issue by BubuAnabelas** [linuxmint/mintupgrade#21]
Before **Phase 3: Upgrade** if the user quits the upgrader tool, it should automatically rollback the sources lists to the old version.

**Why?**
Because if you decide to not upgrade right now and you quit, but you do it later and run the tool again it will do the apt checks and cause havoc updating and deleting orphaned packages.

This was exactly what I did and ended up having to run the checks and upgrading the packages manually (without GUI because after restarting the computer cinnamon was broken).

**Comment by clefebvre** [comment]
OK, it probably needs to check what you're pointing to and skip some early steps if you're already on destination repos.

For the rollback though we rely on timeshift as a requirement. This simplifies things greatly.
