### ISSUE TITLE
Upgrading to 21, mintupgrade crashed during final phase "No module named 'imp'"

### ISSUE THREAD

**Issue by mmortal03** [linuxmint/mintupgrade#28]
While upgrading to 21, mintupgrade crashed during the final phase with: "No module named 'imp'"

See error output in image.
![IMG_20220807_233355498](https://user-images.githubusercontent.com/8298277/183372929-689cdb77-97b5-4a4a-ac6d-cb7186af8263.jpg)

**Comment by clefebvre** [comment]
thanks @mmortal03 looking at the code I can see what's going on.

I think the check is detecting a change in fstab during the upgrade and trying to show that info. There's an issue in the code because the check doesn't have an icon name defined. We'll get this fixed.
