### ISSUE TITLE
Typo in translation in the installer (login/password)

### ISSUE THREAD

**Issue by adevoss** [linuxmint/mintupgrade#29]
When using the installer at a given moment you are asked to type username and password for the new user.

In the Dutch translation of 'ask for password' there is the word 'vergen'.
This should be 'vragen' (to ask)

Please feel free to move this issue to another repo. I'm not sure this is the correct one.

**Comment by devn1x** [comment]
The repo for the installer present in the live environment is [linuxmint/ubiquity](https://github.com/linuxmint/ubiquity/). My dutch is not that good, but as far as I can tell, vergen means something like "require":
https://www.deepl.com/en/translator#nl/en/Mijn%20wachtwoord%20vergen%20om%20aan%20te%20melden

**Comment by adevoss** [comment]
Thanks for the redirect to the other repo.
