### ISSUE TITLE
An unclear instruction: 'Add the packages you want to keep using the preferences' 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintupgrade#32]
What preferences, please? No other GUI window is showing.

![image](https://user-images.githubusercontent.com/47056543/183451115-d958d260-dc89-498c-b241-587e3071b374.png)

**Comment by Xmetalfanx** [comment]
I am guessing it means to select the app not in the repo (what is in that list) that you want to keep the old preferences for and then hit check again

**Comment by mytlogos** [comment]
You can add orphans to keep in the Preferences Setting of the mintupgrade tool:
1. Click on the three-vertical-dots-button (or bars) in the menu bar
2. click Preferences
3. Select 'Orphan Packages' in the Sidebar
4. Add Orphan Packages by name via '+' Button

The process of adding all packages seems very tedious to me though
![grafik](https://user-images.githubusercontent.com/29383271/183497230-8bacaa80-008d-4a86-ab24-18d37fd3a585.png)

**Comment by ValTM** [comment]
A button beside each package to add it to the whitelist, and a button to add all to the whitelist, would be perfect.
Or just do a table row select with what packages are to be kept.

**Comment by Flixnore** [comment]
I'm upgrading now and was also confused by this instruction, when Googling I found this. Perhaps the language should change from:
"Add the packages you want to keep using the preferences"
to
"Add the packages you want to keep using the Mint Update preferences (found in the title bar)"
or something similar.

**Comment by esaumell** [comment]
I'm also upgrading now and I have to add manually one by one about 20 packages. The problem is that I have to write them down somewhere to have to go to preferences and add them there. Clearly this can be improved.
As said by @ValTM a button to add them all to the whitelist, would be perfect.

**Comment by Jeremy7701** [comment]
It's not straight-forward.
The orphans may have dependencies, but these are unknown because the packages are no longer in the repositories.
So removing orphans during an upgrade is the least worst option.
So you probably need to replace them by using an alternative program or by compiling from source after the upgrade.
It's often the case that packages are orphaned because they no longer have a maintainer.

**Comment by LinuxOnTheDesktop** [comment]
@Jeremy7701 

So there is a problem with automatically re-installing the packages. OK. Could the user not at least be (1) told that, (2) given a copy-pasteable list of the packages?

**Comment by Jeremy7701** [comment]
Yes it should - perhaps it could even write them to a file for you?

**Comment by clefebvre** [comment]
This is no longer relevant, the design changed and the user no longer needs to worry about this.
