### ISSUE TITLE
Alternate backup systems

### ISSUE THREAD

**Issue by Tony-Goat** [linuxmint/mintupgrade#33]
Howdy,

I was running a test upgrade from 20.3 to 21 today using mintupgrade and became rather annoyed with the system snapshot step in the upgrade. I understand it is good practice to take backups of your data before you do the upgrade, however, TimeShift is not the only mechanism through which this is possible.

For example, my workplace has a few Linux Mint virtual machines that we have for certain system maintenance activities, and we always take a VM Snapshot of it before we run big updates on it. And on my personal machine at home, my home partition is on a ZFS pool, which provides snapshotting capabilities similar to BTRFS.

Requiring a TimeShift snapshot to be made for the upgrade is unfortunately annoying to go through when we already have a good, alternate backup system. I think one should be able to skip the TimeShift snapshot, with a big warning box that says "If you don't take a backup and this fails, your data may be lost forever," that way, those with alternate backup systems can proceed, and others know that it is an important step to take before the upgrade, and that they understand the risk if they don't make a backup.

**Comment by mtwebster** [comment]
Hi, you can disable the timeshift check in menu -> Preferences.
![image](https://user-images.githubusercontent.com/262776/183488128-e430ad69-78d7-45d5-bde1-6f96d6d72451.png)
