### ISSUE TITLE
Open window won't minimize after upgrade to 21 

### ISSUE THREAD

**Issue by glasscapt** [linuxmint/mintupgrade#34]
I've found a possible bug in upgrading to 21 on one of my test machines.

If Applet  Workspace Switcher   is enabled, an open window fails to minimize off the screen.  To repair this glitch/bug, I have to right click on panel, Troubleshoot, Reset to defaults, and then the 'minimize from screen to panel' works properly.  

I've had to disable   Workspace Switcher  for now, to avoid breaking the minimize window feature.

This is my Upload System Info...
https://termbin.com/repi

Revision...  Skip the Panel, Troubleshoot, path.  Just disable Workspace Switcher in Applets, and reboot.  That corrected the issue of broken windows minimization.

**Comment by Xmetalfanx** [comment]
if this is after the upgrade worked, (not sure who does the workspace-switcher applet) this may be better reported in the Cinnamon issue list https://github.com/linuxmint/cinnamon/issues

I dont have the official name of the applet in front of me as I am not on Cinnamon but https://github.com/linuxmint/cinnamon-spices-applets/issues may be the place to look too

**Comment by glasscapt** [comment]
I enabled the Workspace Switcher applet to try to produce errors, and noticed the kernel update, so did that first. Upon reboot, the applet is working properly again. Thanks, Dev Team for a speedy repair.

**Comment by glasscapt** [comment]
I was wrong, the kernel update did not fix the issue.  The issue occurs only when a second window is open and then when trying to minimize the window freezes until icon in panel is clicked, then the window can either be closed or max sized or reduce sized; the minimize fails to send the window to the panel.  The window freezes.   Here is a link to the .xsession-errors that was requested.  I'm a strictly gui user, so I may not be much assistance in this matter.    https://paste.opensuse.org/85875582

**Comment by Xmetalfanx** [comment]
can we keep this to one issue vs copy and pasting the same message to the same exact (closed) issue ... no need to have the same conversations on the same issue (in concept) with two github issues on this repo

**Comment by glasscapt** [comment]
Just a mistake as I'm unfamiliar with dealing with GitHub.

    On Wednesday, August 10, 2022 at 04:33:04 AM UTC, Xmetal ***@***.***> wrote:  
 
 


can we keep this to one issue vs copy and pasting the same message to the same exact (closed) issue ... no need to have the same conversations on the same issue (in concept) with two github issues on this repo

**Comment by glasscapt** [comment]
As I can't contribute properly, not being familiar with using cli, I'm closing this issue.  Fortunately, this feature on this LM 21 machine isn't vital for my use case. Thanks for your attention.

**Comment by mtwebster** [comment]
It was fixed today, I just didn't realize there were 2 open issues for it
https://github.com/linuxmint/cinnamon/commit/7dac334cf1ce4507718b00ef9c9ba0f26d8eb965
