### ISSUE TITLE
[Feature Request] Prompt User for Root Privilege when Starting Mintupgrade

### ISSUE THREAD

**Issue by wolfiediscord** [linuxmint/mintupgrade#35]
Currently, you can install mintupgrade from the Software Center, however, it does not open unless you run it through the terminal. Asking the user for their password would allow mintupgrade to run. There could be a separate menu button (Logs) for showing the stdout of the application for troubleshooting purposes. 

This feature would help new users upgrade from their LM versions without having to know the terminal at all.

**Comment by clefebvre** [comment]
The requirement for the terminal is done on purpose. The first thing we ask when troubleshooting an issue is the stdout output. That output isn't always straight forward (APT etc..), the more we interfere with it the more issues can be introduced.
