### ISSUE TITLE
Open window won't minimize after upgrade to 21 

### ISSUE THREAD

**Issue by glasscapt** [linuxmint/mintupgrade#36]
I've found a possible bug in upgrading to 21 on one of my test machines.

If Applet Workspace Switcher is enabled, an open window fails to minimize off the screen. To repair this glitch/bug, I have to right click on panel, Troubleshoot, Reset to defaults, and then the 'minimize from screen to panel' works properly.

I've had to disable Workspace Switcher for now, to avoid breaking the minimize window feature.

This is my Upload System Info...
https://termbin.com/repi

Revision... Skip the Panel, Troubleshoot, path. Just disable Workspace Switcher in Applets, and reboot. That corrected the issue of broken windows minimization.

**Comment by Xmetalfanx** [comment]
Duplicate of https://github.com/linuxmint/mintupgrade/issues/34 and POSSIBLY posted in the wrong repo too (a Cinnamon issue? ... or a Cinnamon-Spices repo issue?... I do not recall if the "Mint Team" does that Workspace Switcher applet or if it's third party)

**Comment by mtwebster** [comment]
If fails to minimize - does it do nothing?  Can you still interact with that window?

Can you paste `~/.xsession-errors` from when this happens?

**Comment by glasscapt** [comment]
I enabled the Workspace Switcher applet to try to produce errors, and noticed the kernel update, so did that first.  Upon reboot, the applet is working properly again.  Thanks, Dev Team for a speedy repair.

**Comment by glasscapt** [comment]
I enabled the Workspace Switcher applet to try to produce errors, and noticed the kernel update, so did that first. Upon reboot, the applet is working properly again. Thanks, Dev Team for a speedy repair.

**Comment by glasscapt** [comment]
I found that after a second window is opened, the window fails to minimize.  The window freezes until I click on the icon of it in the panel, which will then allow the close and max/reduce buttons to function.  If I disable Workplace Switcher applet, then the window buttons work fine.  I was mistaken when I reported that the kernel repaired the issue.  I'm a gui only user, so I'm stumbling around trying to report this minor glitch.  I'm not sure this answers your request, but this link is what I did find that relates to .xsession-errors.
https://paste.opensuse.org/85875582







    On Tuesday, August 9, 2022 at 03:36:32 PM CDT, Michael Webster ***@***.***> wrote:  
 
 


If fails to minimize - does it do nothing? Can you still interact with that window?

Can you paste ~/.xsession-errors from when this happens?

**Comment by glasscapt** [comment]
Not knowing enough about cli usage to contribute properly, I'm going to close this issue.  Fortunately, the feature on that LM 21 machine isn't vital for my use case.  Thanks for your attention.
