### ISSUE TITLE
Invalid 'kept' package shown

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/mintupgrade#4]
Package **0ad** listed as a 'kept' package, despite never having been installed (its the first package, alphabetically).

![Screenshot from 2022-04-12 00-39-52](https://user-images.githubusercontent.com/52585119/162853057-3fb90819-363c-474c-9852-b4bd4a5a9735.png)

**Comment by xenopeek** [comment]
I've seen the same on two test upgrades today. It is indeed the very first package in the package cache, which is probably wrong.

The code here https://github.com/linuxmint/mintupgrade/blob/master/usr/lib/linuxmint/mintupgrade/checks.py#L581 finds that the keep_count is 1 and then tries to find the marked_keep package and returns Oad. But if I remove that break there, it returns almost 60000 packages -> the marked_keep is true for all despite the keep_count being 1

**Comment by clefebvre** [comment]
Confirmed.

**Comment by Jeremy7701** [comment]
**0ad** is available in two versions in bullseye (according to synaptic):-
0.0.25b-1~bpo11+1 (bullseye-backports)
and
0.0.23.1-5+b1 (stable)

Perhaps the code is counting 0ad twice???

**Comment by xenopeek** [comment]
The kept package is guile-2.2-libs. This is discoverable in the terminal output, just before the GUI shows the kept package:
```
Running check 'Upgrade simulation'
tester@lmde:~$ 
Running check 'Package download'
DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get dist-upgrade --download-only --yes
<cut for brevity>
The following packages have been kept back:
  guile-2.2-libs
```
I don't know why marked_keep doesn't work as we think on the cache.

As an alternative, this code will get the correct list of kept packages:
```
import apt
cache = apt.Cache()
cache.upgrade(True)
changes = cache.get_changes()
kept_packages = []

# Replace this code:
#        if cache.keep_count > 0:
#            # kept packages are not part of the changes...
#            num_found = 0
#            for pkg in cache:
#                if pkg.marked_keep:
#                    kept_packages.append(pkg.name)
#                    num_found += 1
#                if num_found == cache.keep_count:
#                    break
if cache.keep_count > 0:
	upgradable_cache_packages = [pkg.name for pkg in cache if pkg.is_upgradable]
	upgradable_changes_packages = [pkg.name for pkg in changes if pkg.is_upgradable]
	kept_packages = list(set(upgradable_cache_packages).difference(set(upgradable_changes_packages)))
```
That returns ['guile-2.2-libs'] for me. Which is correct.

**Comment by Jeremy7701** [comment]
Confirmed.
I kept a full log of the upgrade process [12,158 lines]:-

The following packages will be REMOVED:
  g++-8 gcc-8 gvfs-fuse libebook-1.2-19 libedata-book-1.2-25 libedata-cal-1.2-29 libfwup1 libgcc-8-dev
  libgladeui-2-6 libgnome-desktop-3-17 libgtk2-perl libldb1 libmailutils5 libmetacity1 libpolkit-backend-1-0
 [...]
**The following packages have been kept back:
  guile-2.2-libs**
The following packages will be upgraded:
  accountsservice acl acpi-support acpi-support-base acpid adwaita-icon-theme alsa-utils amd64-microcode
  anacron apg apparmor appstream apt apt-clone apt-transport-https apt-utils aptdaemon aptdaemon-data
[...]

**Comment by clefebvre** [comment]
Fixed.
