### ISSUE TITLE
Mintupgrade fails when non 'standard' LibreOffice is installed

### ISSUE THREAD

**Issue by pnewbery** [linuxmint/mintupgrade#43]
This issue is similar to #27, but involves LibreOffice as opposed to PHP.
Upgrading to Mint 21.0 from 20.3 Una fails at the Foreign packages check with the following output:

Running check 'Foreign packages'

Fixing check 'Foreign packages'
DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get install --allow-downgrades -fyq -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-overwrite" fonts-opensymbol=2:102.11+LibO6.4.7-0ubuntu0.20.04.4 libjuh-java=1:6.4.7-0ubuntu0.20.04.4 libjurt-java=1:6.4.7-0ubuntu0.20.04.4 liblibreoffice-java=1:7.2.7-0ubuntu0.21.10.1~bpo20.04.1 libuno-cppu3=1:6.4.7-0ubuntu0.20.04.4 libuno-cppuhelpergcc3-3=1:6.4.7-0ubuntu0.20.04.4 libuno-purpenvhelpergcc3-3=1:6.4.7-0ubuntu0.20.04.4 libuno-sal3=1:6.4.7-0ubuntu0.20.04.4 libuno-salhelpergcc3-3=1:6.4.7-0ubuntu0.20.04.4 libunoil-java=1:6.4.7-0ubuntu0.20.04.4 libunoloader-java=1:6.4.7-0ubuntu0.20.04.4 uno-libs-private=1:6.4.7-0ubuntu0.20.04.4 ure=1:6.4.7-0ubuntu0.20.04.4 ure-java=1:7.2.7-0ubuntu0.21.10.1~bpo20.04.1
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 liblibreoffice-java : Breaks: libjuh-java (< 1:7.1.0~)
                       Breaks: libjurt-java (< 1:7.1.0~)
                       Breaks: libunoil-java (< 1:7.1.0~)
 ure-java : Depends: uno-libs-private (= 1:7.2.7-0ubuntu0.21.10.1~bpo20.04.1) but 1:6.4.7-0ubuntu0.20.04.4 is to be installed
            Depends: ure (= 1:7.2.7-0ubuntu0.21.10.1~bpo20.04.1) but 1:6.4.7-0ubuntu0.20.04.4 is to be installed
            Breaks: ure (< 1:7.1.0~) but 1:6.4.7-0ubuntu0.20.04.4 is to be installed
E: Unable to correct problems, you have held broken packages.
Error - Return code: 100

Clicking Either the 'Fix' or 'Check Again' buttons yields exactly the same output.

Running any of the normal broken package fixes: dpkg --configure -a or apt install -f etc. has no effect.

I suspect this error is occurring because I removed the standard version of LibreOffice (currently 6.4.7.2 on fully updated Mint 20.3) to install version 7.3.2.2 even though this version is still lower than that installed by mintupgrade viz: 7.3.5.2

**Comment by monsta** [comment]
It tries to downgrade `ure-java` to the version from "focal-backports" repo while downgrading its dependencies to the version from the main "focal" repo - this will never work. That package doesn't exist in the main "focal" repo, so mintupgrade should've removed it instead of downgrading, but it doesn't do that.

Use `ppa-purge` tool to downgrade libreoffice properly - it will do it correctly, removing `ure-java`.

**Comment by Jeremy7701** [comment]
Was there a **really good reason** for applying the LibreOffice Mint 20.3 upgrade outside the normal update/upgrade cycle?

**Comment by pnewbery** [comment]
Well, I've been doing quite a bit of database & spreadsheet work lately for our small charity and I like to ensure that I have the latest version so that I have the cutting edge features for maximum compatibility with MS office. I note that LO is now offered as an Appimage so I will probably delete the base version and go with that.
