### ISSUE TITLE
Power Source Warning

### ISSUE THREAD

**Issue by MrHumanRebel** [linuxmint/mintupgrade#45]
![mint](https://user-images.githubusercontent.com/80947401/185658253-4fb7103b-032c-4b9c-8f07-4f505f225840.jpg)

My laptop is charging, and the warning does not go away no matter what I do.
How can I bypass this check?

server@server:~$ sudo mintupgrade
Running check 'Phase 1: Preparation'
APT Repositories:
Repos:
  No active apt repos in: /etc/apt/sources.list 
  Active apt repos in: /etc/apt/sources.list.d/jellyfin.list 
  1: deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
  1: deb https://quantum-mirror.hu/mirrors/linuxmint/packages una main upstream import backport
  2: deb http://repo.jztkft.hu/ubuntu focal main restricted universe multiverse
  3: deb http://repo.jztkft.hu/ubuntu focal-updates main restricted universe multiverse
  4: deb http://repo.jztkft.hu/ubuntu focal-backports main restricted universe multiverse
  5: deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
  6: deb http://archive.canonical.com/ubuntu/ focal partner
Running check 'Linux Mint version'
Check succeeded:  Linux Mint version
Running check 'Power source'
Running check 'Power source'
Running check 'Power source'
Running check 'Power source'

**Comment by devn1x** [comment]
I don't know if this is still relevant but:

You can't really bypass this check. But you can look at the output of `acpi -a`. This is whats used internally to check if power is connected. If the output contains "off-line" anywhere, it will fail.

**Comment by MrHumanRebel** [comment]
server@server:~$ acpi -a
Adapter 0: off-line
server@server:~$ 


This is what I get.

**Comment by MrHumanRebel** [comment]
> I don't know if this is still relevant but:
> 
> You can't really bypass this check. But you can look at the output of `acpi -a`. This is whats used internally to check if power is connected. If the output contains "off-line" anywhere, it will fail.

![image](https://user-images.githubusercontent.com/80947401/192345573-b0b36f1a-6c23-4843-a695-ce5bbcce1432.png)

**Comment by devn1x** [comment]
This seems to be a problem not related to mintupgrade. Maybe ask around on the forum or in chat:
https://linuxmint.com/contactus.php

Alternatively, if want to file a bug report on why `acpi -a` is not recognizing that the battery is charging, you can submit one at
https://launchpad.net/ubuntu/+source/acpi/+bugs.
Although it is probably a good idea to reproduce this acpi issue with a ubuntu live system before, to verify it is actually an issue coming from ubuntu.

And maybe this page could be useful as well:
https://wiki.ubuntu.com/DebuggingACPI

**Comment by Jeremy7701** [comment]
You could always (temporarily) replace `/usr/bin/acpi` with a command (called acpi) that outputs "No support for device type: power_supply" which is what you should get on a desktop. Probably best to keep the original somewhere, so that you can replace it later.

acpi -a
No support for device type: power_supply
