### ISSUE TITLE
apache2 was enabled preventing nginx from listening on port 80

### ISSUE THREAD

**Issue by RafaelKr** [linuxmint/mintupgrade#49]
As part of https://github.com/cpriego/valet-linux I had nginx running as system service which autostarted by default.

I think after the upgrade from 20.3 to 21 apache2 was autostarting because the systemd service was enabled again and nginx couldn't start anymore.

**Comment by clefebvre** [comment]
Thanks for reporting this. Mintupgrade doesn't enable this itself, but the debian packaging probably does.

**Comment by RafaelKr** [comment]
@clefebvre Is there any path to take from here? Do you know another place to report this?
