### ISSUE TITLE
upgrade tool error - Overflow during disk space check

### ISSUE THREAD

**Issue by paleoGeek** [linuxmint/mintupgrade#50]
I was upgrading from v20.3 to 21 using the Upgrade Tool, and during the upgrade simulation I got an error that Traceback says is in line 739 of /usr/lib/linuxmint/mintupgrade/checks.py, in check_disk_space requirements. It reports an OverflowError.:

![Screenshot from 2022-09-15 09-38-29](https://user-images.githubusercontent.com/113705211/190700830-8da8a8ad-44d6-4942-a67b-b8db60348ae3.png)

I have 527 GB of free space in the ext4 filesystem, so it is not an actual disk space problem. Line 739 says:

> self.info.append(_("Download size: %s. Additional space needed: %s.") % (GLib.format_size(download_size), GLib.format_size(additional_space_needed)))

and if I change it to

> self.info.append(_("Download size: %s. Additional space needed: .") % (GLib.format_size(download_size) ))

then it does not report the error and continues to a sucssesful upgrade to v21. So the error is in the GLib.format_size(additional_space_needed) call. Note that the Kept packages window includes a line that says "Download size: 2.3 GB. Additional space needed:." so that seems to be where the value is used. Maybe it is the wrong type?

If it matters, it happened when I was in the process of upgrading from v18 to v21 using the steps in [https://linuxmint-user-guide.readthedocs.io/en/latest/upgrade.html]. This was the output of inxi -SDPxx before attempting the v20.3 to v21 upgrade:

System:
  Host: transit Kernel: 4.15.0-20-generic x86_64 bits: 64 compiler: gcc 
  v: 7.3.0 Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM 
  Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
Drives:
  Local Storage: total: 931.51 GiB used: 377.97 GiB (40.6%) 
  ID-1: /dev/sda vendor: Toshiba model: DT01ACA100 size: 931.51 GiB 
  speed: <unknown> serial: 66UWMS7NS 
Partition:
  ID-1: / size: 909.92 GiB used: 377.97 GiB (41.5%) fs: ext4 dev: /dev/sda1 
  ID-2: swap-1 size: 6.95 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda5

**Comment by Logan5GreyE** [comment]
I also get the same error. How did you change this?

**Comment by Logan5GreyE** [comment]
Photo for reference

**Comment by paleoGeek** [comment]
> I also get the same error. How did you change this?

Once I removed the GLib.format_size(additional_space_needed) call in checks.py as described above, it completed without error.

**Comment by aminalshmu** [comment]
Thanks for this tip, I had issues with the upgrade (also from 20.3 to 21) and had to restart many times for other reasons and eventually started getting this error. To save time for anyone else with the issue, checks.py is in /usr/lib/linuxmint/mintupgrade

Kudos paleoGeek!
