### ISSUE TITLE
Still expecting answer about the differences, possible risks  and why mintupgrade doesn't do it automatically

### ISSUE THREAD

**Issue by nicolasmol** [linuxmint/mintupgrade#51]
Following the thread https://github.com/linuxmint/mintupgrade/issues/27.
I'm still expecting an answer why doing this...
```
sudo sed -i 's/focal/jammy/' /etc/apt/sources.list.d/official-package-repositories.list 
sudo apt full-upgrade
```
...which I did not apply until ultimate patching (therefore I'm still under 20.3), seems to be a also a valid and easier way to upgrade without pre-removing the so said "broken packages" (php-generic packages in my case); and if it's an equivalent job : why mintupgrade doesn't to this by itself before ?

**Comment by clefebvre** [comment]
No this just works around the problem. By pointing to the destination you basically make it skip a whole series of tests. It solves your particular issue but it would also make it unable to detect a series of potential issues for other users.
