### ISSUE TITLE
Do not use --purge on orphaned packages

### ISSUE THREAD

**Issue by kfeoktistoff** [linuxmint/mintupgrade#53]
Hi all,

Last time I upgraded from Mint 20.3 to 21 the upgrading script found several orphaned packages. Most of them were considered orphaned because they were installed from 3rd party repository which did not have packages for Jammy at the upgrade time. Here is an incomplete list of the packages: pgadmin3, postgresql-12, dolphin-emu, julia, android-tools-adb and other.

After the upgrade I updated the repositories in `/etc/apt/sources.list.d/` and reinstalled the packages but because they were removed with `--purge` option, I had to reconfigure them again.

Thus, will it be feasible to drop `--purge` argument [here](https://github.com/linuxmint/mintupgrade/blob/18807e3fada93fae4e6e91956eb1e1a765b82c0b/usr/lib/linuxmint/mintupgrade/checks.py#L524)? If necessary, a user can purge the removed packages manually later using, e.g. this [solution](https://askubuntu.com/a/687318/332792).

**Comment by Jeremy7701** [comment]
I detected some unwanted configuration files in LMDE5 by running  `dpkg --get-selections | awk '$2 == "deinstall" {print $1}'` which produced a short list of non-existent packages (which I then removed with `apt purge ...`).

**Comment by clefebvre** [comment]
This is no longer relevant to mintupgrade. We only remove only newly orphaned pkgs now.
