### ISSUE TITLE
[Feature request] Improve ergonomic of adding foreign packages to keep 

### ISSUE THREAD

**Issue by MikeNavy** [linuxmint/mintupgrade#54]
Hi,
In mintupgrade, settings, there is the possibility to make a list of foreign packages to keep. However, it is a long and tedious process:
- user has 1st to establish the list of obsolete packages, and this point is not documented (I did it with "apt list ?obsolete >list.txt" command),
- then user has to transfer the list of packages one by one: copy the package name from the list, paste it in mintupgrade list of foreign packages window, the clik on "validate" button; this takes a lot of time if there are several tens of packages to keep.

Proposed improvement of UI:
- the list of existing foreign packages is shown in the foreign packages to keep, by default unselected,
- user can select them one by one (by a tick on a case) or can select all (by a button to click on).

Regards,
MN

**Comment by flanaman** [comment]
Came here to ask for this as well. Even just being able to copy the list of orphan packages to a text file would be good. This way we can have that list open at the same time we are adding them in the preferences. (Checkboxes would be way better, though.)

**Comment by clefebvre** [comment]
This is fixed. Only newly orphaned pkgs are removed now.
