### ISSUE TITLE
Upgrade to 21 throws error on 'Final phase'

### ISSUE THREAD

**Issue by tefdos** [linuxmint/mintupgrade#57]
I'm getting an error on the upgrade final phase with message in terminal:

> Running check 'Final phase'
Re-installing the meta-package
DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get install --yes --no-install-recommends mint-meta-  file /usr/local/bin/crudini, line 39
    print str(e)
    ^^^^^^^^^^^^
syntaxerror: missing parentheses in call to 'print'. did you mean print(...)?
Reading package lists...
E: Unsupported file /usr/local/bin/crudini, given on commandline
/bin/sh: 2: Syntax error: "(" unexpected
Error - Return code: 2

Any suggestions on how to proceed with the upgrade?

**Comment by carlosmintfan** [comment]
Try to run `apt install --reinstall crudini`.
