### ISSUE TITLE
Linux Mint MATE not bootable after 20.3 upgrade to 21 - obsolete greeter

### ISSUE THREAD

**Issue by guy-rouillier** [linuxmint/mintupgrade#59]
Please see forum post https://forums.linuxmint.com/viewtopic.php?f=46&t=380340&p=2248178#p2248178 for additional info.

In brief, the upgrade process reported that it had completed successfully, but when I rebooted, the main boot option would not bring up the system.  It showed the Mint green circle, but just stayed there; it never displayed the login prompt.  I tapped Delete to see the log messages, and reported those in my forum post.

I was able to boot to the 2nd option, Advanced options, and then selected recovery mode.  From there, I selected the "resume" option, logged in through the terminal, and then entered startx.  The usual desktop displayed.

To get to the problem, under 20.3 I was using the webkit greeter. I don't remember how I ended up with that.  But 21 apparently no longer supports the webkit greeter.  Once I selected and installed a different greeter - gtk-greeter - the system could then boot normally.

This sequence will confound a less experienced user.  When a greeter is removed, mintupgrade should check if the user's system is using that greeter.  If so, mintupgrade should abort the upgrade process, since the resulting system configuration will not boot.  mintupgrade should then explain that the system is using a greeter that is no longer supported, and instruct the user to switch to a supported greeter before running the upgrade again.

**Comment by clefebvre** [comment]
It's definitely a valid issue, but I think you're asking too much of the upgrader here. The greeter by default is slick-greeter. If you switch it to another one, that's a specific system administration decision, not only something we can't/shouldn't question or go against, but also something a casual user would not do. In terms of scope, how many such examples should we detect, care for, prevent, forbid? If we scan this, force down slick-greeter, I mean.. I can think of tens of other examples where an admin could replace a default system component, we can't detect them all.
