### ISSUE TITLE
No obvious way to preserve held packages (at user's risk).

### ISSUE THREAD

**Issue by lumixdeee** [linuxmint/mintupgrade#67]
Mintupgrading from lmde 4 to lmde 5.

Very happy to see an option to specify any orphan packages you wish to keep. I almost used mintupgrade.

Then found no way to proceed without unholding three packages. The three are : grub2-theme-mint mint-x-icons mint-y-icons

I have held these three packages when upgrading from cindy via debbie to elsie dozens of times and nothing has broken, however, later versions of these packages DO break my preferred lmde configuration.

Could there be a flag or an option to overrule the enforced release of held packages, with suitable warnings to the user of course.

Today I had to go back to the manual upgrade method, because I know from experience that downgrading these packages after upgrade does not achieve the same results as keeping them held.

This is not about me using mintupgrade wrongly. It is about whether or not I use it at all.

**Comment by Jeremy7701** [comment]
I have all 3 of these packages in LMDE5 (Elsie) currently installed.
The upgrade simply replaced the LMDE4 versions with appropriate upgraded versions.

**Comment by lumixdeee** [comment]
Jeremy, I want to keep the LMDE 3 versions of the packages.
As I said, upgrading them then downgrading them does not work.

Which versions do you have installed now?

**Comment by Jeremy7701** [comment]
These packages would appear to be strongly dependent on major packages:-
**apt-cache rdepends grub2-theme-mint mint-x-icons mint-y-icons**
```
grub2-theme-mint
Reverse Depends:
  debian-system-adjustments
  mint-meta-core
mint-x-icons
Reverse Depends:
  mint-artwork
  mint-themes
mint-y-icons
Reverse Depends:
  mint-artwork
  mint-themes-legacy
  mint-themes
```
Versions:-
**apt-cache policy grub2-theme-mint mint-x-icons mint-y-icons**
```
grub2-theme-mint:
  Installed: 1.2.2
  Candidate: 1.2.2
  Version table:
 *** 1.2.2 500
        500 https://mirror.netcologne.de/linuxmint/packages elsie/main amd64 Packages
        500 https://mirror.netcologne.de/linuxmint/packages elsie/main i386 Packages
        100 /var/lib/dpkg/status
mint-x-icons:
  Installed: 1.6.4
  Candidate: 1.6.4
  Version table:
 *** 1.6.4 500
        500 https://mirror.netcologne.de/linuxmint/packages elsie/main amd64 Packages
        500 https://mirror.netcologne.de/linuxmint/packages elsie/main i386 Packages
        100 /var/lib/dpkg/status
mint-y-icons:
  Installed: 1.6.4
  Candidate: 1.6.4
  Version table:
 *** 1.6.4 500
        500 https://mirror.netcologne.de/linuxmint/packages elsie/main amd64 Packages
        500 https://mirror.netcologne.de/linuxmint/packages elsie/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by lumixdeee** [comment]
What appears from inspection of those returned values is merely a hope.
Only testing can tell us what we have actually got. No other software development activity has this superpower.
In testing of live systems upgrading from Cindy to Elsie, holding those three packages has the following impact on other packages: none.

If there is a material impact that you have found, please provide steps to reproduce.

**Comment by clefebvre** [comment]
Because so many things can go wrong or require advanced manual intervention.. the too makes basic assumptions and requirements which simplify the process and reduce the possibility of different use cases. One of them is for your all packages to upgrade properly.

I understand your particular need here, but in this case I'd recommend a manual upgrade (terminal, using APT tools directly).
