### ISSUE TITLE
Mint update reports DeprecationWarning in .xsession-errors of Linux Mint 21.2 Cinnamon

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/mintupgrade#71]
.xsession-errors is collecting quite a few errors about mintupdate deprecation.

mintupdate 6.0.3 on Linux mint 21.2 Cinnamon.   Not running dev or beta versions, just good ole stable.

/usr/lib/linuxmint/mintUpdate/mintUpdate.py:1368: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:1751: DeprecationWarning: Gdk.threads_enter is deprecated
  Gdk.threads_enter()
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:796: DeprecationWarning: Gdk.threads_leave is deprecated
  Gdk.threads_leave()

**Comment by clefebvre** [comment]
Only warnings for now. Likely to be fixed for Mint 22. This is about mintupdate though, not mintupgrade.
