### ISSUE TITLE
Failed LMDE 5 to 6 Upgrade due to sticky

### ISSUE THREAD

**Issue by Den-of-Bees** [linuxmint/mintupgrade#79]
![Screenshot from 2024-01-25 02-10-33](https://github.com/linuxmint/mintupgrade/assets/130232931/50c8473f-f439-4362-9fd4-62a3d8332917)
![22](https://github.com/linuxmint/mintupgrade/assets/130232931/c625e2ea-39a1-4e83-9239-a405019cbfdb)

Setting up sticky (1.19) ...
  File "/usr/lib/sticky/sticky.py", line 765
    match method_name:
          ^
SyntaxError: invalid syntax

**Comment by Den-of-Bees** [comment]
followed direction, updated and removed foreign packages prior to upgrade attempt

**Comment by bit-man** [comment]
Happened to me too. Workaround was to comment the whole `dbus_method_callback` method (lines 764 to 774) and press `Check again` button

Given that match/case was introduced at [Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching) and maybe upgrade tool is using a prior Python version?

**Comment by jmh79** [comment]
I encountered this while upgrading LMDE 5 to 6 in VirtualBox. The simplest solution I found was to remove the `sticky` package before starting the upgrade and re-install it afterwards.

LMDE 5 came with Python 3.9 while LMDE 6 has 3.11. I'm guessing `mintupgrade` not only decided to upgrade `sticky` before `python3`, but also tried to run the new `sticky` during the upgrade process, causing Python 3.9 to throw the syntax error.

**Comment by carlosmintfan** [comment]
I added a PR to sticky that may fix this :rocket:

**Comment by neil-o** [comment]
While awaiting a fix for this bug to be adopted, could there be a warning about it, and a suggested work-around, posted in the Release Notes?   [https://linuxmint.com/rel_faye.php](https://linuxmint.com/rel_faye.php)  

The work-around of simply removing _sticky_ before the upgrade, and then reinstalling it after the upgrade, is easy enough for non-expert users to accomplish, but is not likely to be discovered until the attempt to upgrade fails.  I believe it would not occur to most users to consult the issue tracker for the _minutupgrade_ package before attempting an upgrade.

**Comment by carlosmintfan** [comment]
> While awaiting a fix for this bug to be adopted, could there be a warning about it, and a suggested work-around, posted in the Release Notes? https://linuxmint.com/rel_faye.php
> 
> The work-around of simply removing _sticky_ before the upgrade, and then reinstalling it after the upgrade, is easy enough for non-expert users to accomplish, but is not likely to be discovered until the attempt to upgrade fails. I believe it would not occur to most users to consult the issue tracker for the _minutupgrade_ package before attempting an upgrade.

I don't think so. It's just for the team to get attention to this, if they can add that to the release notes, they can also merge the pull request. It's all in the linuxmint org, sticky too.

**Comment by lutin11** [comment]
Also affected by this problem, removing **sticky** package solve the problem
