### ISSUE TITLE
Bug: requirement for a Timeshift snapshot, a possible critical barrier while Timeshift ZFS locations useless

### ISSUE THREAD

**Issue by rwperrott** [linuxmint/mintupgrade#86]
The Mint Installer, at least for the latest Mint 21provides the options to install Linux Mint on ZFS.

TimeShift may support backing up a ZFS system, but only shows the useless /dev/device path for the ZFS pools, not actually useful ZFS datasets, including for /root. The result is that upgrade is only possible if a suitable non-ZFS location, can be configured as a location for Timeshift. This may not be the case if all drives with sufficient free space only contain only a ZFS pool, as I'd leaning towards.

See also [Timeshift #56](https://github.com/linuxmint/timeshift/issues/56)

**Comment by rwperrott** [comment]
I spotted this issue when I used mintupgrade for Mint 22, and was annoyed that I had to keep at least one internal drive, in each upgraded machine, not in a ZFS pool, so that I could create the required fresh Timeshift "snapshot".

**Comment by clefebvre** [comment]
ZFS support was removed from 22.

However note that the timeshift snapshot is not a requirement in mintupgrade. You can disable it in the preferences.

**Comment by rwperrott** [comment]
> ZFS support was removed from 22.

I assume that the ZFS option was dropped in 22 as a side-effect of what appeared to be a bug/mistake in the Ubuntu 23.04 installer, because Ubuntu restored the ZFS option in the Ubuntu 23.10 installer, as noted at https://www.phoronix.com/news/Ubuntu-23.10-ZFS-Install

> 
> However note that the timeshift snapshot is not a requirement in mintupgrade. You can disable it in the preferences.

Fine, I may not have noticed that.
