### ISSUE TITLE
LMDE 4 : Missing dep make an error

### ISSUE THREAD

**Issue by aaaaadrien** [linuxmint/mintupgrade#9]
Hello
Running the beta version, error at Step 3. crudini command not found.
In Step1, check if crudini package installed. If no, install it !

**Comment by mtwebster** [comment]
Did you install it as instructed in the blog? The crudini package is already a dependency, and should have been installed when you ran `apt install mintupgrade`

**Comment by aaaaadrien** [comment]
Installed from sourcecode here

**Comment by mtwebster** [comment]
So this won't happen ordinarily.. There's no need to check for it at runtime.

**Comment by aaaaadrien** [comment]
Okay.
I installed before the beta version which are in the repo !
it's good with the deb
