### ISSUE TITLE
Can not find matrix after upgrade to LM22

### ISSUE THREAD

**Issue by ritulahkar** [linuxmint/mintupgrade#90]
How to install or get the matrix app, it's not there.

**Comment by jeremyb31** [comment]
`sudo apt install mintchat`

**Comment by clefebvre** [comment]
You can just make a new webapp using the following link: https://app.element.io/#/room/#linuxmint-space:matrix.org

**Comment by jeremyb31** [comment]
Is there any issue with just adding that URL to mintwelcome similar to what was used to link IRC?
