### ISSUE TITLE
Ctrl-C aborts the upgrade immediately and ungraciously

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintupgrade#94]
Given that the GUI is open, and the important nature of the upgrade process, one does not except a single ctrl-C - which I executed because, in the terminal, apt appeared to have hung - to terminate the whole upgrade process, without any confirmation (even, though, happily, I was merely in the 'simulation' phase of the upgrade).

Screenshot:

![image](https://github.com/user-attachments/assets/3157a95a-9dab-4682-a01c-441560f12e2d)

EDITED for clarity.

**Comment by clefebvre** [comment]
I get your point, though Ctrl+C is specifically designed to terminate output commands and expected to do so.
