### ISSUE TITLE
Erroneous $PATH in Mint22 - it contains /snap/bin

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/mintupgrade#95]
Snaps are rightly disabled, but $PATH contains /snap/bin - even though this directory doesn't exist.

$PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by clefebvre** [comment]
That's OK I think, it's inherited from upstream's .profile and all afaik.
