### ISSUE TITLE
mintupgrade 21.3 to 22 - source.list.d DEB822 not supported yet ?

### ISSUE THREAD

**Issue by leonardinux** [linuxmint/mintupgrade#96]
Hi all.
During mintupdate I have this warning beacuse I use winehq from their stable ubuntu repos:

![Schermata del 2024-07-29 08-17-08](https://github.com/user-attachments/assets/43982165-63c1-4ff0-9359-0d8a2ea3d710)

But in 21.3 it works|||

Can I ignore it and change from "wine jammy repos" to "wine noble repos" after the mintupgrade?
Or must I do it before?

TNX de leonardinux (aka IZ5FSA)

**Comment by clefebvre** [comment]
It's supported by APT but not by mintupgrade yet. You can remove the repository prior to upgrading and then re-add it once you're on 22.
