### ISSUE TITLE
Mintupgrade removed apps it shouldn't to, and failed to install new ones

### ISSUE THREAD

**Issue by eugenialoli** [linuxmint/mintupgrade#99]
I just upgraded from 21.3 to 22. However, the upgrade procedure did these two things:

1. It removed apps that it shouldn't, like Celluloid, and VLC. After the upgrade, I had no media player at all, not even the default Mint one.
2. It failed to install the new Matrix app.

My husband's laptop was a clean installation and all the apps were installed properly. My three (upgradeable from 21.3) laptops with Mint though had the same problem: removal of apps (more so than the scheduled downgrade of gnome apps), and it didn't install the new apps, like matrix.

**Comment by jeremyb31** [comment]
There is no Matrix app, it is a simple program called mintchat, install in terminal with `sudo apt install mintchat`

**Comment by eugenialoli** [comment]
I know that, I'm not trying to get user support here. The point is that this is a bug. It should have installed, since this was an upgrade, and an upgrade should install the new stuff. Otherwise we get an inconsistency between upgrades and clean installations, and that's never good.

**Comment by clefebvre** [comment]
Upgraded systems shouldn't be identical to freshly installed one. The priority is to keep things as they are more so than to reflect every single change. Mintchat is there for new users only, the Matrix webapp isn't added during the upgrade.

There's a fix for VLC and Celluloid. I'd need more info on the mintupgrade version and the upgrade log to identify this as still being an issue.

https://github.com/linuxmint/mintupgrade/commit/002722081ec333609cf79140b79184dd4189c433
https://github.com/linuxmint/mintupgrade/commit/0fbb1fd760f25bff64e89bbdccd7ae69a25a3bb4
